HomeAutomation.Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HomeAutomation.Models.Wrappers;
using Microsoft.AspNet.Identity;
using HomeAutomation.Services.Interfaces;
using HomeAutomation.Services.Abstract;
using HomeAutomation.Controllers.Abstract;

namespace HomeAutomation.Controllers
{
	[Authorize]
    public class DashboardController : BaseController
    {
		public DashboardController(IServiceHolder ss) : base(ss)
        {
		}

        // GET: Dashboard
        public ActionResult Index()
        {
			DashboardIndexViewModel viewModel = SS.DashboardService.PopulateViewModelForUser(User.Identity.GetUserId());

			ViewBag.UserId = User.Identity.GetUserId();

			return View(viewModel);
        }
		
		[HttpPost]
		[ValidateAntiForgeryToken]
		public JsonResult GetLocationKeysForUser(string userId)
		{
			List<LocationKeyWrapper> keysForUser = SS.LocationKeyService.GetLocationKeysForUser();

			return Json(keysForUser);
		}
	}
}

HomeAutomation.Web/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HomeAutomation.DAL;
using HomeAutomation.Models.Entities;
using Microsoft.AspNet.Identity;
using HomeAutomation.Services.Interfaces;
using HomeAutomation.Services.Abstract;
using HomeAutomation.Controllers.Abstract;
using HomeAutomation.ViewModels.Devices;

namespace HomeAutomation.Controllers
{
    [Authorize]
    public class DevicesController : BaseController
    {
        public DevicesController(IServiceHolder ss) : base(ss)
        {
        }

        // GET: Devices
        public ActionResult Index()
        {
            var devices = SS.DeviceService.GetAllForUser();
            return View(devices.ToList());
        }

        // GET: Devices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = SS.DeviceService.GetSingleForUser(id.Value);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // GET: Devices/Create
        public ActionResult Create()
        {
            var locationsForUser = SS.LocationService.GetAllForUser();

            ViewBag.LocationId = new SelectList(locationsForUser, "Id", "Name");

            return View();
        }

        // POST: Devices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AddEditDeviceViewModel deviceVM)
        {
            if (ModelState.IsValid)
            {
                var device = new Device()
                {
                    Name = deviceVM.Name,
                    Description = deviceVM.Description,
                    LocalIP = deviceVM.LocalIP,
                    Port = deviceVM.Port,
                    LocationId = deviceVM.LocationId,
                    Type = deviceVM.Type,
                    OwnerId = CurrentUserId,
                };

                SS.DeviceService.Add(device);

                return RedirectToAction("Index");
            }

            var locationsForUser = SS.LocationService.GetAllForUser();
            
            ViewBag.LocationId = new SelectList(locationsForUser, "Id", "Name", deviceVM.LocationId);
            return View(deviceVM);
        }

        // GET: Devices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = SS.DeviceService.GetSingleForUser(id.Value);
            if (device == null)
            {
                return HttpNotFound();
            }

            var locationsForUser = SS.LocationService.GetAllForUser();

            ViewBag.LocationId = new SelectList(locationsForUser, "Id", "Name", device.LocationId);
            return View(new AddEditDeviceViewModel(device));
        }

        // POST: Devices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AddEditDeviceViewModel device)
        {
            if (ModelState.IsValid)
            {
                var entry = SS.DeviceService.GetSingleForUser(device.Id);
                entry.Name = device.Name;
                entry.Description = device.Description;
                entry.LocalIP = device.LocalIP;
                entry.Port = device.Port;
                entry.Type = device.Type;

                SS.DeviceService.Update(entry);
                return RedirectToAction("Index");
            }

            return View(device);
        }

        // GET: Devices/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = SS.DeviceService.GetSingleForUser(id.Value);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: Devices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SS.DeviceService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

HomeAutomation.Web/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HomeAutomation.DAL;
using HomeAutomation.Models.Entities;
using HomeAutomation.ViewModels.Locations;
using Microsoft.AspNet.Identity;
using HomeAutomation.Services.Interfaces;
using HomeAutomation.Controllers.Abstract;
using HomeAutomation.Services.Abstract;

namespace HomeAutomation.Controllers
{
	[Authorize]
	public class LocationsController : BaseController
	{
		public LocationsController(IServiceHolder ss) : base(ss)
        {
		}
        

		// GET: Locations
		public ActionResult Index()
		{
			var locations = SS.LocationService.GetAllForUser();
			return View(locations.ToList());
		}

		// GET: Locations/Details/5
		public ActionResult Details(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			Location location = SS.LocationService.GetSingleForUser(id.Value);

			if (location == null)
			{
				return HttpNotFound();
			}

			return View(location);
		}

		// GET: Locations/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: Locations/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(AddEditLocationViewModel location)
		{
			if (!ModelState.IsValid)
			{
				return View(location);
			}

            Location locationToAdd = new Location()
            {
                Name = location.Name,
                Description = location.Description,
                LocationURL = location.LocationURL,
                Port = location.Port,
                MasterKey = location.MasterKey,
                IsVerified = false,
                OwnerId = CurrentUserId
            };

            SS.LocationService.Add(locationToAdd);

            return RedirectToAction("Index");
		}

		// GET: Locations/Edit/5
		public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			Location location = SS.LocationService.GetSingleForUser(id.Value);

			if (location == null)
			{
				return HttpNotFound();
			}

			AddEditLocationViewModel vm = new AddEditLocationViewModel(location);
			return View(vm);
		}

		// POST: Locations/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(AddEditLocationViewModel moddedLoc)
		{
			if (!ModelState.IsValid)
			{
				return View(moddedLoc);
			}

            Location existingLoc = SS.LocationService.GetSingleForUser(moddedLoc.Id);

            if (existingLoc.LocationURL != moddedLoc.LocationURL || existingLoc.Port != moddedLoc.Port || existingLoc.MasterKey != moddedLoc.MasterKey)
            {
                existingLoc.IsVerified = false;
            }

            existingLoc.Name = moddedLoc.Name;
            existingLoc.Description = moddedLoc.Description;
            existingLoc.LocationURL = moddedLoc.LocationURL;
            existingLoc.Port = moddedLoc.Port;
            existingLoc.MasterKey = moddedLoc.MasterKey;

            SS.LocationService.Update(existingLoc);

            return RedirectToAction("Index");
		}

        public ActionResult Verify(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Location location = SS.LocationService.GetSingleForUser(id.Value);

            if (location == null)
            {
                return HttpNotFound();
            }

            bool success = SS.LocationService.VerifyLocation(location);

            return Json(success, JsonRequestBehavior.AllowGet);
        }

		// GET: Locations/Delete/5
		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			Location location = SS.LocationService.GetSingleForUser(id.Value);

			if (location == null)
			{
				return HttpNotFound();
			}

			return View(location);
		}

		// POST: Locations/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			SS.LocationService.Delete(id);

			return RedirectToAction("Index");
		}
	}
}

HomeAutomation.Web/Views/Dashboard/Index.cshtml
@using HomeAutomation.Models.Wrappers
@using HomeAutomation.Models.Enumeration
@model DashboardIndexViewModel

@{
    ViewBag.Title = "Dashboard";
    ViewBag.HidePageHeader = true;
}

<div id="user-info"
     data-user-id="@ViewBag.UserId">
    @Html.AntiForgeryToken()
</div>

<!-- Small boxes (Stat box) -->
<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>@Model.LocationCount</h3>
                <p>Locations</p>
            </div>
            <div class="icon">
                <i class="ion ion-location"></i>
            </div>
            <a href="@Url.Action("Index", "Locations")" class="small-box-footer"> <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h3>@Model.DevicesCount</h3>
                <p>Devices</p>
            </div>
            <div class="icon">
                <i class="ion ion-gear-b"></i>
            </div>
            <a href="@Url.Action("Index", "Devices")" class="small-box-footer"> <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>@Model.LocationsSharedFromOtherUsersCount</h3>
                <p>Locations shared from other users</p>
            </div>
            <div class="icon">
                <i class="ion ion-share"></i>
            </div>
            <a href="#" class="small-box-footer"> <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h3>@Model.TotalAvailableLocations</h3>
                <p>Total available locations</p>
            </div>
            <div class="icon">
                <i class="ion ion-information-circled"></i>
            </div>
            <a href="#" class="small-box-footer"> <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
</div>
<!-- /.row -->

@foreach (UserLocationWrapper location in Model.UserLocations)
{
    @RenderLocationBlock(location);
}

@section scripts {
    <script src="~/Scripts/Custom/dashboard-switch.js"></script>
    <script src="~/Scripts/Custom/dashboard-core.js"></script>
    <script src="~/Scripts/Custom/dashboard-app.js"></script>
}


@helper RenderLocationBlock(UserLocationWrapper location)
{
    <div class="locationHolder">
        <div class="row">
            <div class="col-lg-12">
                <h2>@location.Name</h2>
            </div>
        </div>
        <div class="row clearfix">
            @foreach (var device in location.UserDevices)
            {
                @RenderDeviceBlock(device);
            }
        </div>
    </div>
}

@helper RenderDeviceBlock(UserDeviceWrapper device)
{
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
        <div class="info-box deviceHolder"
             data-id="@device.Id"
             data-local-address="@device.LocalAddress"
             data-deviceType="@device.Type"
             data-location-id="@device.LocationId">
            @switch (device.Type)
            {
                case DeviceType.Sensor:
                    @RenderDeviceBlockForSensor(device);
                    break;
                case DeviceType.Switch:
                    @RenderDeviceBlockForSwitch(device);
                    break;
                case DeviceType.Slider:
                    @RenderDeviceBlockForSlider(device);
                    break;
                case DeviceType.TextSender:
                    @RenderDeviceBlockForTextSender(device);
                    break;
                default:
                    <p>Device type not supported.</p>break;
            }
        </div>
        <!-- /.info-box -->
    </div>
}

@helper RenderDeviceBlockForSensor(UserDeviceWrapper device)
{
    <div class="deviceInit_Sensor">
        <span class="info-box-icon bg-aqua"><i class="fa fa-dashboard"></i></span>

        <div class="info-box-content">
            <span class="info-box-text">@device.Name</span>
            <h3 class="deviceStatus">---</h3>
        </div>
    </div>
}

@helper RenderDeviceBlockForSwitch(UserDeviceWrapper device)
{
    <div class="deviceInit_Switch" data-is-checking-status="0" data-is-running-user-command="0">
        <span class="info-box-icon bg-green"><i class="fa fa-power-off"></i></span>

        <div class="info-box-content">
            <span class="info-box-text">@device.Name</span>
            @*<span class="deviceStatus">---</span>*@
            <br />
            <div class="btn-group switch-control-container" data-toggle="buttons">
                <label class="switch-control switch-on btn btn-default" data-val="1">
                    <input type="radio" name="switchControl" id="@string.Format("switch{0}", device.Id)" autocomplete="off"> On
                </label>
                <label class="switch-control switch-off btn btn-default" data-val="0">
                    <input type="radio" name="switchControl" id="@string.Format("switch{0}", device.Id)" autocomplete="off"> Off
                </label>
            </div>
        </div>
    </div>
}

@helper RenderDeviceBlockForSlider(UserDeviceWrapper device)
{
    <div class="deviceInit_Slider">
        <span class="info-box-icon bg-orange"><i class="fa fa-sliders"></i></span>

        <div class="info-box-content">
            <span class="info-box-text">@device.Name</span>
            <div>
                Not supported yet
            </div>
        </div>
    </div>
}

@helper RenderDeviceBlockForTextSender(UserDeviceWrapper device)
{
    <div class="deviceInit_TextSender">
        <span class="info-box-icon bg-red"><i class="fa fa-font"></i></span>

        <div class="info-box-content">
            <span class="info-box-text">@device.Name</span>
            <div>
                Not supported yet
            </div>
        </div>
    </div>
}