HomeAutomation.Web/ViewModels/Permissions/AddEditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HomeAutomation.ViewModels.Permissions
{
    public class AddEditViewModel
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int LocationId { get; set; }
        public int DeviceId { get; set; }
        public bool IsFullControlPermission { get; set; }
    }
}

HomeAutomation.Web/ViewModels/Permissions/LocationPermissionViewModel.cs
using System.Collections.Generic;
using HomeAutomation.Models.Entities;

namespace HomeAutomation.ViewModels.Permissions
{
    public class LocationPermissionViewModel
    {
        public Location Location { get; set; }
        public bool HasFullPermissions { get; set; }
        public List<Device> AllowedDevices { get; set; }
    }
}

HomeAutomation.Web/ViewModels/Permissions/UserPermissionsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using HomeAutomation.Models.Entities;

namespace HomeAutomation.ViewModels.Permissions
{
    public class UserPermissionsViewModel
    {
        public UserPermissionsViewModel(Dictionary<Location, IEnumerable<Device>> permissions)
        {
            LocationPermissions = new List<LocationPermissionViewModel>();

            if (permissions.Count > 0)
            {
                foreach (var kvp in permissions)
                {
                    LocationPermissionViewModel temp = new LocationPermissionViewModel();
                    temp.Location = kvp.Key;

                    if (kvp.Value == null)
                    {
                        temp.HasFullPermissions = true;
                    }
                    else
                    {
                        temp.HasFullPermissions = false;
                        temp.AllowedDevices = kvp.Value.ToList();
                    }

                    LocationPermissions.Add(temp);
                }
            }
        }

        public List<LocationPermissionViewModel> LocationPermissions { get; set; }
    }
}

HomeAutomation.Web/Controllers/PermissionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HomeAutomation.DAL;
using HomeAutomation.Models.Entities;
using HomeAutomation.ViewModels.Permissions;
using Microsoft.AspNet.Identity;
using HomeAutomation.Services.Interfaces;
using HomeAutomation.Controllers.Abstract;
using HomeAutomation.Services.Abstract;

namespace HomeAutomation.Controllers
{
    [Authorize]
    public class PermissionsController : BaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public PermissionsController(ApplicationDbContext context, IServiceHolder ss) : base(ss)
        {
            db = context;
        }

        // GET: Permissions
        public ActionResult Index(int? id)
        {
            var users = SS.PermissionService.GetAllUsersWithPermissionsForUserDevices();
            //var devicePermissions = db.DevicePermissions.Include(d => d.Device).Include(d => d.LocationKey);
            return View(users.ToList());
        }

        // GET: Permissions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DevicePermission devicePermission = db.DevicePermissions.Find(id);
            if (devicePermission == null)
            {
                return HttpNotFound();
            }
            return View(devicePermission);
        }

        // GET: Permissions/Create
        public ActionResult Create()
        {
            string currentUserId = User.Identity.GetUserId();
            ViewBag.DeviceId = new SelectList(db.Devices, "Id", "Name");
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name");
            ViewBag.UserId = new SelectList(db.Users.Where(u => u.Id != currentUserId), "Id", "UserName");

            return View();
        }

        // POST: Permissions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AddEditViewModel permission)
        {
            if (ModelState.IsValid)
            {
                if (permission.IsFullControlPermission)
                {
                    SS.PermissionService.AddLocationPermission(permission.UserId, permission.LocationId);
                }
                else
                {
                    SS.PermissionService.AddDevicePermission(permission.UserId, permission.LocationId, permission.DeviceId);
                }

                return RedirectToAction("Index");
            }

            string currentUserId = User.Identity.GetUserId();
            ViewBag.DeviceId = new SelectList(db.Devices, "Id", "Name");
            ViewBag.LocationId = new SelectList(db.Locations, "Id", "Name");
            ViewBag.UserId = new SelectList(db.Users.Where(u => u.Id != currentUserId), "Id", "UserName");

            return View(permission);
        }

        // GET: Permissions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DevicePermission devicePermission = db.DevicePermissions.Find(id);
            if (devicePermission == null)
            {
                return HttpNotFound();
            }
            ViewBag.DeviceId = new SelectList(db.Devices, "Id", "Name", devicePermission.DeviceId);
            ViewBag.LocationKeyId = new SelectList(db.LocationKeys, "Id", "Key", devicePermission.LocationKeyId);
            return View(devicePermission);
        }

        // POST: Permissions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,LocationKeyId,DeviceId,DateCreated,DateModified")] DevicePermission devicePermission)
        {
            if (ModelState.IsValid)
            {
                db.Entry(devicePermission).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DeviceId = new SelectList(db.Devices, "Id", "Name", devicePermission.DeviceId);
            ViewBag.LocationKeyId = new SelectList(db.LocationKeys, "Id", "Key", devicePermission.LocationKeyId);
            return View(devicePermission);
        }

        [HttpPost]
        public ActionResult RevokeForUser(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            SS.PermissionService.RevokeRightsForUser(id);

            return RedirectToAction("Index");
        }

        // GET: Permissions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DevicePermission devicePermission = db.DevicePermissions.Find(id);
            if (devicePermission == null)
            {
                return HttpNotFound();
            }
            return View(devicePermission);
        }

        // POST: Permissions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DevicePermission devicePermission = db.DevicePermissions.Find(id);
            db.DevicePermissions.Remove(devicePermission);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ForUser(string id)
        {
            var permissions = SS.PermissionService.GetAssignedPermissionsForUser(id);

            UserPermissionsViewModel vm = new UserPermissionsViewModel(permissions);

            return View(vm);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HomeAutomation.Web/Views/Permissions/Create.cshtml
@model HomeAutomation.ViewModels.Permissions.AddEditViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      <h4>DevicePermission</h4>
      <hr />

      @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      <div class="form-group">
        @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
          @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.LocationId, "LocationId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.DropDownList("LocationId", null, htmlAttributes: new { @class = "form-control" })
          @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.IsFullControlPermission, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          <div class="checkbox">
            @Html.EditorFor(model => model.IsFullControlPermission)
            @Html.ValidationMessageFor(model => model.IsFullControlPermission, "", new { @class = "text-danger" })
          </div>
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.DeviceId, "DeviceId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.DropDownList("DeviceId", null, htmlAttributes: new { @class = "form-control" })
          @Html.ValidationMessageFor(model => model.DeviceId, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <input type="submit" value="Create" class="btn btn-default" />
        </div>
      </div>
    </div>
}

<div>
  @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
  @Scripts.Render("~/bundles/jqueryval")
}

HomeAutomation.Web/Views/Permissions/Delete.cshtml
@model HomeAutomation.Models.Entities.DevicePermission

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DevicePermission</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Device.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Device.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationKey.Key)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationKey.Key)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HomeAutomation.Web/Views/Permissions/Details.cshtml
@model HomeAutomation.Models.Entities.DevicePermission

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DevicePermission</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Device.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Device.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationKey.Key)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationKey.Key)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HomeAutomation.Web/Views/Permissions/Edit.cshtml
@model HomeAutomation.Models.Entities.DevicePermission

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DevicePermission</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.LocationKeyId, "LocationKeyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationKeyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationKeyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeviceId, "DeviceId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DeviceId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DeviceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateModified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateModified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeAutomation.Web/Views/Permissions/ForUser.cshtml
@model HomeAutomation.ViewModels.Permissions.UserPermissionsViewModel

@{
    ViewBag.Title = "ForUser";
}
<p>
  @Html.ActionLink("Create New", "Create")
</p>
<div class="box">
  <div class="box-body">
    <table class="table table-hover table-bordered">
      <tr>
        <th>
          Location
        </th>
        <th>
          Has full control?
        </th>
        <th></th>
      </tr>

      @foreach (var locationPerm in Model.LocationPermissions)
      {
          <tr>
            <td>
              @Html.DisplayFor(modelItem => locationPerm.Location.Name)
            </td>
            <td>
              @Html.DisplayFor(modelItem => locationPerm.HasFullPermissions)
            </td>
            <td>
              @*@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })*@
            </td>
          </tr>
        if (!locationPerm.HasFullPermissions && locationPerm.AllowedDevices.Count > 0)
        {
              <tr>
                <td colspan="3">
                  <table class="table">
                    <tr>
                      <th>
                        Device
                      </th>
                      <th>
                        Type
                      </th>
                    </tr>
                    @foreach (var device in locationPerm.AllowedDevices)
                    {
                        <tr>
                          <td>
                            @device.Name
                          </td>
                          <td>
                            @device.Type
                          </td>
                        </tr>
                    }
                    <tr></tr>
                  </table>
                </td>
              </tr>
        }
      }
    </table>
  </div>
</div>

HomeAutomation.Web/Views/Permissions/Index.cshtml
@model IEnumerable<HomeAutomation.Models.Account.ApplicationUser>

@{
    ViewBag.Title = "Users with permissions for my locations and devices";
}

<p>
    <a href="@Url.Action("Create")" class="btn btn-primary">
        New access rule
    </a>
</p>

<div class="box">
    <div class="box-body">
        <table class="table table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.UserName)
                </th>
                <th>
                </th>
                <th>
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.ActionLink("List of permissions", "ForUser", new { id = item.Id })


                    </td>
                    <td>
                        @using (Html.BeginForm("RevokeForUser", "Permissions"))
                        {
                            @Html.AntiForgeryToken()

                            <input type="hidden" value="@item.Id" name="id" />
                            <input type="submit" value="Revoke" class="btn btn-danger" />
                        }
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

HomeAutomation.Web/Views/Permissions/whatever.cshtml
@model HomeAutomation.Models.Entities.LocationKey

@{
    ViewBag.Title = "whatever";
}

<h2>whatever</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>LocationKey</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsMasterKey, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsMasterKey)
                    @Html.ValidationMessageFor(model => model.IsMasterKey, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HasFullDeviceControl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.HasFullDeviceControl)
                    @Html.ValidationMessageFor(model => model.HasFullDeviceControl, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsVerified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsVerified)
                    @Html.ValidationMessageFor(model => model.IsVerified, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerId, "OwnerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OwnerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OwnerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, "LocationId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateModified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateModified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}